Check overflow, preserve atomicity, and enhance feasibility.
ucare-uchicago/FEMU pull request #40
Opened 2021-01-06 06:24 UTC by HongweiQin

This patch does three things. (Sorry to violate the "one patch does one thing" policy. I can separate the pull requests if you insist.)

1. Check user configuration overflows.
We should check user channel and PU configurations when starting FEMU. Incorrect configurations may lead to array overflows.

2. Preserve access atomicity to shared resources.
When the multi_poller feature is enabled, chip_next_avail_time[] and chnl_next_avail_time[] are shared resources. Therefore, we should use locks to avoid race conditions.

3. Enhance FEMU feasibility.
Currently, for OCSSD write requests, FEMU assumes the request size is fixed to 32KiB. This is true for PBLK but may be false for other host-side FTLs. This patch enable FEMU to correctly handle write requests that are larger than 32KiB.

2021-01-10 21:42 UTC, huaicheng requested changes
better fix the indentation of line 952

2021-01-11 01:47 UTC, huaicheng reviewed
Did you measure how much performance overhead this extra per-chnl/chip lock would bring? e.g., under a read-only fio workload with QD=128. More specifically perf numbers for the following three cases would be useful:

- 1 poller + no-lock (disable multi-poller)
- N pollers + no-lock (current HEAD)
- N pollers + lock (your patch)

Another thing is ``chip_next_avail_time[]`` and ``chnl_next_avail_time[]`` should be part of the ``FemuCtrl`` structure, otherwise the timing emulation won't be accurate under multiple FEMU-emulated OCSSDs. This is not introduced by your design, maybe it's better to fix this in a separate patch.

2021-01-11 01:51 UTC, huaicheng reviewed
Let's squash all the changes into one patch .. I will review the new patch again later on. It's a good idea to keep an eye on the trivial spacing/indent issues (not a big deal though).

Thanks for the patches!!

2021-01-11 05:28 UTC, HongweiQin commented
Thanks for the review. 

> better fix the indentation of line 952

Fixed.

> Did you measure how much performance overhead this extra per-chnl/chip lock would bring? e.g., under a read-only fio workload with QD=128. More specifically perf numbers for the following three cases would be useful:
> 
> * 1 poller + no-lock (disable multi-poller)
> * N pollers + no-lock (current HEAD)
> * N pollers + lock (your patch)

I will do some tests later on.

2021-01-14 02:38 UTC, HongweiQin commented
Hi Huaicheng,
Here are some quick results using pblk and fio. I first fill up the device. Then, use the following command to test

# Method
Command:
```
fio -numjobs=$nThreads -bs=4096 -filename=/dev/${target}dev tools/randread  | grep "read: IOPS="
```

fio script:
```
[global]
thread
kb_base=1000
direct=1
group_reporting
time_based=1
runtime=30
ioengine=libaio
iodepth=128
iodepth_batch_submit=1
iodepth_batch_complete=1

[fio_randread]
size=70%
rw=randread
```

# Results

## Current Head Disable Multi Poller

```
*******************************
Rand Read Test, nr_threads=1
  read: IOPS=125k, BW=512MB/s (489MiB/s)(15.4GB/30002msec)
 
*******************************
Rand Read Test, nr_threads=1
  read: IOPS=117k, BW=478MB/s (456MiB/s)(14.3GB/30001msec)
 
*******************************
Rand Read Test, nr_threads=2
  read: IOPS=160k, BW=657MB/s (627MiB/s)(19.7GB/30001msec)
 
*******************************
Rand Read Test, nr_threads=2
  read: IOPS=167k, BW=686MB/s (654MiB/s)(20.6GB/30001msec)
 
*******************************
Rand Read Test, nr_threads=3
  read: IOPS=217k, BW=888MB/s (847MiB/s)(26.6GB/30003msec)
 
*******************************
Rand Read Test, nr_threads=3
  read: IOPS=269k, BW=1102MB/s (1050MiB/s)(33.0GB/30001msec)
 
*******************************
Rand Read Test, nr_threads=4
  read: IOPS=185k, BW=757MB/s (722MiB/s)(22.7GB/30003msec)
 
*******************************
Rand Read Test, nr_threads=4
  read: IOPS=329k, BW=1346MB/s (1284MiB/s)(40.4GB/30001msec)

*******************************
Rand Read Test, nr_threads=32
  read: IOPS=242k, BW=992MB/s (947MiB/s)(29.8GB/30002msec)
 
*******************************
Rand Read Test, nr_threads=32
  read: IOPS=282k, BW=1154MB/s (1100MiB/s)(34.6GB/30002msec)
 
*******************************
Rand Read Test, nr_threads=16
  read: IOPS=319k, BW=1308MB/s (1248MiB/s)(39.2GB/30001msec)
 
*******************************
Rand Read Test, nr_threads=16
  read: IOPS=222k, BW=910MB/s (868MiB/s)(27.3GB/30005msec)
 
*******************************
Rand Read Test, nr_threads=8
  read: IOPS=120k, BW=493MB/s (470MiB/s)(14.8GB/30006msec)
 
*******************************
Rand Read Test, nr_threads=8
  read: IOPS=142k, BW=582MB/s (555MiB/s)(17.5GB/30003msec)

```

## Current Head Disable Multi Poller

```
*******************************
Rand Read Test, nr_threads=1
  read: IOPS=90.3k, BW=370MB/s (353MiB/s)(11.1GB/30001msec)
 
*******************************
Rand Read Test, nr_threads=1
  read: IOPS=106k, BW=436MB/s (416MiB/s)(13.1GB/30001msec)
 
*******************************
Rand Read Test, nr_threads=2
  read: IOPS=185k, BW=756MB/s (721MiB/s)(22.7GB/30001msec)
 
*******************************
Rand Read Test, nr_threads=2
  read: IOPS=192k, BW=787MB/s (750MiB/s)(23.6GB/30001msec)
 
*******************************
Rand Read Test, nr_threads=3
  read: IOPS=246k, BW=1006MB/s (959MiB/s)(30.2GB/30001msec)
 
*******************************
Rand Read Test, nr_threads=3
  read: IOPS=239k, BW=979MB/s (934MiB/s)(29.4GB/30001msec)
 
*******************************
Rand Read Test, nr_threads=4
  read: IOPS=331k, BW=1355MB/s (1292MiB/s)(40.6GB/30001msec)
 
*******************************
Rand Read Test, nr_threads=4
  read: IOPS=325k, BW=1331MB/s (1269MiB/s)(39.9GB/30001msec)

 
*******************************
Rand Read Test, nr_threads=32
  read: IOPS=409k, BW=1676MB/s (1598MiB/s)(50.3GB/30006msec)
 
*******************************
Rand Read Test, nr_threads=32
  read: IOPS=415k, BW=1700MB/s (1622MiB/s)(51.0GB/30003msec)

*******************************
Rand Read Test, nr_threads=16
  read: IOPS=500k, BW=2048MB/s (1953MiB/s)(61.4GB/30001msec)
 
*******************************
Rand Read Test, nr_threads=16
  read: IOPS=491k, BW=2010MB/s (1917MiB/s)(60.3GB/30001msec)
 
*******************************
Rand Read Test, nr_threads=8
  read: IOPS=555k, BW=2273MB/s (2167MiB/s)(68.2GB/30002msec)
 
*******************************
Rand Read Test, nr_threads=8
  read: IOPS=555k, BW=2274MB/s (2169MiB/s)(68.2GB/30002msec)

```

## Patch Enable Multi Poller

```
*******************************
Rand Read Test, nr_threads=32
  read: IOPS=394k, BW=1616MB/s (1541MiB/s)(48.5GB/30002msec)
 
*******************************
Rand Read Test, nr_threads=32
  read: IOPS=401k, BW=1641MB/s (1565MiB/s)(49.2GB/30004msec)
 
*******************************
Rand Read Test, nr_threads=16
  read: IOPS=481k, BW=1970MB/s (1879MiB/s)(59.1GB/30002msec)
 
*******************************
Rand Read Test, nr_threads=16
  read: IOPS=478k, BW=1956MB/s (1865MiB/s)(58.7GB/30002msec)
 
*******************************
Rand Read Test, nr_threads=8
  read: IOPS=567k, BW=2321MB/s (2214MiB/s)(69.6GB/30001msec)
 
*******************************
Rand Read Test, nr_threads=8
  read: IOPS=470k, BW=1926MB/s (1837MiB/s)(57.8GB/30001msec)

*******************************
Rand Read Test, nr_threads=32
  read: IOPS=415k, BW=1699MB/s (1621MiB/s)(50.0GB/30004msec)
 
*******************************
Rand Read Test, nr_threads=16
  read: IOPS=488k, BW=1999MB/s (1906MiB/s)(59.0GB/30001msec)
 
*******************************
Rand Read Test, nr_threads=8
  read: IOPS=526k, BW=2155MB/s (2055MiB/s)(64.7GB/30001msec)
 
*******************************
Rand Read Test, nr_threads=4
  read: IOPS=345k, BW=1413MB/s (1347MiB/s)(42.4GB/30001msec)
 
*******************************
Rand Read Test, nr_threads=2
  read: IOPS=194k, BW=794MB/s (757MiB/s)(23.8GB/30001msec)
 
*******************************
Rand Read Test, nr_threads=1
  read: IOPS=117k, BW=479MB/s (457MiB/s)(14.4GB/30001msec)

```

2021-01-14 02:57 UTC, HongweiQin commented
Please note that:

1. There are 8 hardware queues.
2. The multi-poller feature is useful when the host uses multi-thread to issue I/Os. Take a look at nrThreads=8,16, and 32.
3. You might wonder why the throughput of 32 threads is less than that of 8 threads. This is a scaling issue of pblk. One of the contributions of my recent project QBLKe ([https://github.com/WNLO-DSAL/QBLKe](https://github.com/WNLO-DSAL/QBLKe)) addresses this issue. Checkout the following results:

```
Current Head Disable Multi-poller:
Rand Read Test, nr_threads=32
  read: IOPS=262k, BW=1075MB/s (1025MiB/s)(32.3GB/30007msec)

Current Head Enable Multi-poller:
Rand Read Test, nr_threads=32
  read: IOPS=904k, BW=3702MB/s (3530MiB/s)(111GB/30008msec)

Patch:
Rand Read Test, nr_threads=32
  read: IOPS=902k, BW=3695MB/s (3523MiB/s)(111GB/30006msec)

```

Let's discuss about this if you have any questions.

2021-01-14 16:00 UTC, huaicheng commented
Looks good to me. The main goal of this test is to verify the locking overhead. But it seems to be marginal from your tests, which is great.

Thanks.

2021-01-14 16:01 UTC, huaicheng approved these changes

2021-01-14 16:03 UTC, huaicheng approved these changes

2021-01-14 16:06 UTC, merged