Fix selecting gc line wrong in BlackBox mode
ucare-uchicago/FEMU pull request #61
Opened 2021-09-13 12:43 UTC by ywang-wnlo

victim_line_pq (using minheap) is not always valid, because the line's priority may be changed while `mark_page_invalid`

2021-09-19 00:46 UTC, huaicheng commented
Hi,

Nice catch!! Could you squash the commits into one patch and I review it soon. Thank you for reporting this!

2021-09-19 01:55 UTC, ywang-wnlo commented
I do not know how to squash it, because I have two bugs fixed, so I force push for this one. If it will be merged, I will pull another one soon!

2021-09-19 23:07 UTC, huaicheng requested changes
See the comments. Do you mind making some small changes as suggested? Happy to merge it afterwards. Thanks!

2021-09-19 23:07 UTC, huaicheng commented on hw/block/femu/bbssd/ftl.c
> +    }
The logic here is problematic:

``line->vpc--`` is always needed as one page is being marked as invalid, thus it shouldn't be put into the ``else`` statement. Change it to something like:

```
line->vpc--; 
if (line->pos) {
    pqueue_change_priority(lm->victim_line_pq, line->vpc, line);
}
```

Also, note that the "priority" for the priority queue is just ``line->vpc``, why do you put ``line->vpc-1`` here?

2021-09-19 23:07 UTC, huaicheng commented on hw/block/femu/lib/pqueue.c
> +static size_t minchild(pqueue_t *q, size_t i)
OK, I don't see logic changes for ``lib/pqueue.c`` here, and I suggest we discard the changes.

- the renaming is fine, but it relies on how ``cmp_pri`` is defined to determine whether it's "max" or "min".
- after ``pqueue_pop()``, ``->pos`` won't mean anything until next time it's re-added to the heap (which will adjust its ``->pos`` correctly), so we don't need the change on Line 183.

Note this library is adapted from an implementation used for Apache, thus, unless it's really a bug, I'd prefer not to touch it.

2021-09-20 01:13 UTC, ywang-wnlo commented on hw/block/femu/bbssd/ftl.c
> +    }
`pqueue_change_priority` need new pri and old pri, and cmp then, than choose `bubble_up` or `percolate_down`.

```c
void pqueue_change_priority(pqueue_t *q, pqueue_pri_t new_pri, void *d)
{
    size_t posn;
    pqueue_pri_t old_pri = q->getpri(d);
    q->setpri(d, new_pri);
    posn = q->getpos(d);
    if (q->cmppri(old_pri, new_pri))
        bubble_up(q, posn);
    else
        percolate_down(q, posn);
}
```

2021-09-20 01:16 UTC, ywang-wnlo commented on hw/block/femu/bbssd/ftl.c
> +    }
If we change the vpc before call this func, that means the old pri is equal to the new. That is meaningless to call this func.

2021-09-20 01:25 UTC, huaicheng commented on hw/block/femu/bbssd/ftl.c
> +    }
You're right. Didn't look into ``pqueue_change_priority()`` carefully. But ``line->vpc--`` should be outside of ``else`` anyways.

Actually, using ``pqueue_change_priority()`` is an overkill here. The whole reason of using pqueue for victim lines is to have for fetching the victim line in O(1) during GC, but now the overhead to maintain the pqueue is too high as almost every overwrite would trigger one ``pqueue_change_priority()``. I think the ideal way to handle this is to postpone ``pqueue_change_priority()`` until GC needs to be kicked in. That means we need to maintain a list of victim lines whose positions in the pqueue need to be updated later. Thoughts?

2021-09-20 01:29 UTC, ywang-wnlo commented on hw/block/femu/lib/pqueue.c
> +static size_t minchild(pqueue_t *q, size_t i)
- Abort max or min, that's my mistake.I will roll back for it.
- However, the pos set to 0, can help us judge the item is or not in the pqueue. As you've said, it is tThird-party librarie, so we can change the pos after call `pqueue_pop()` by using `q->setpos`.

I will change the code soon. Thanks for your replay!

2021-09-20 01:40 UTC, ywang-wnlo commented on hw/block/femu/bbssd/ftl.c
> +    }
`pqueue_change_priority` is O(log n), while we just change the pri by `-1`, so it will only take O(1). The overhead is Acceptable.

In fact, we can use the Linked-List directly, and the O(n) time complexity of gc is fine. Because, gc needs to erase super-block(one line), and it will have a delay of a few ms(erase block time) for emulate timeline(erase block time), which can hide this time overhead.

2021-09-20 01:53 UTC, huaicheng commented on hw/block/femu/bbssd/ftl.c
> +    }
No, that's not 100% true. It's still O(log n), and it happens more frequently now (basically roughly every over-writes). 

The old implementations is basically only using a linked list for victim lines, and perform O(n) search to find the ideal victim line. The overhead here is the "computing" overhead, rather than I/O. Ideally, FEMU needs to spend least time in finishing simulating the GC process, and goes back to handle normal I/Os. The longer GC computations would cause potential queue delays on timely processing the rest of normal I/Os.

OK, I decided that this is something that's worthwhile to benchmark later. For now, let's just fix this bug and deem it done. Thanks for your contributions!

2021-10-03 21:45 UTC, merged

2021-10-03 21:46 UTC, huaicheng commented
I will made some changes on top of your current fix. Merge it for now. Thanks for the contributions!